### PR TITLE
Check for nil before calling #each in ancestry.

### PR DESCRIPTION
**Pull request by nuclearsandwich**
With ancestry configurations loaded from YAML. An empty category will be `nil`rather than an empty array. So we need to handle that in the children and parent finding methods.

@gjtorikian I always have a terrible time setting up the fixtures for this repo. What's your suggestion on getting failures in for testing?

cc @lynnwallenstein since we paired on this among other things.

### CODE REVIEW

**Comment by gjtorikian** [comment]
> I always have a terrible time setting up the fixtures for this repo. What's your suggestion on getting failures in for testing?

Yeah, it is a bit of a mess. I usually start with two files:

* `nil_children.md` which is the source. In this case it'd probably be just an empty text file, like the others in the `children` folder
* `nil_children.html`, which contains the output.

Then, you'd create your bogus category in `data/categories/nil_children.yml` or something:

``` yaml
no_children:
```

Finally, you'd up `nanoc.yml` to associate the new category with the new page:

```
  -
    scope:
      path: "nil_children"
    values:
      data_association: "categories.nil_children"
```

After that it should generate the output as expected, from which you can add the new test.

**Comment by nuclearsandwich** [comment]
Spent some time working on the test per @gjtorikian's advice but got pulled into other things before I had functioning fixtures. Hopefully sort that out early next week.

**Comment by nuclearsandwich** [comment]
@gjtorikian I didn't add an explicit test for the nil checks because their absence :boom:s the entire test suite now the nil category is present. If I can get this and #3 together we'll probably call that the next release.

**Comment by gjtorikian** [comment]
Do you need help with me for something specific? I implicitly accept all your changes!

**Comment by nuclearsandwich** [comment]
> Do you need help with me for something specific? I implicitly accept all your changes!

not at this point, just keeping you apprised. This is just a bugfix but since #3 changes external behavior I'll be releasing 0.7.0 with these changes included.

**Pull request merged**
